# Generated by Django 5.2.4 on 2025-07-09 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_color_varient'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='color_varient',
            field=models.ManyToManyField(blank=True, to='product.color_varient'),
        ),
    ]
