# Generated by Django 5.2.4 on 2025-07-12 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_category_slug_alter_product_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='color_varient',
        ),
        migrations.RemoveField(
            model_name='size_varient',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='size_varient',
            field=models.ManyToManyField(blank=True, to='product.size_varient'),
        ),
    ]
