# Generated by Django 5.2.4 on 2025-07-12 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_remove_product_color_varient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='short_desc',
            field=models.CharField(default='', max_length=400),
        ),
    ]
