# Generated by Django 5.2.4 on 2025-07-12 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_alter_product_short_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='short_desc',
            field=models.CharField(default='', max_length=50),
        ),
    ]
