# Generated by Django 5.2.4 on 2025-07-16 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_alter_product_short_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(max_length=225),
        ),
        migrations.AlterField(
            model_name='color_varient',
            name='color_name',
            field=models.CharField(max_length=225),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(max_length=225),
        ),
        migrations.AlterField(
            model_name='product',
            name='short_desc',
            field=models.CharField(default='', max_length=225),
        ),
        migrations.AlterField(
            model_name='size_varient',
            name='size_name',
            field=models.CharField(max_length=225),
        ),
    ]
