# Generated by Django 5.2.4 on 2025-07-16 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_alter_shippingaddress_address_line1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddress',
            name='phone_no',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
